# Generated by Django 5.1.6 on 2025-04-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
