# Generated by Django 5.1.6 on 2025-04-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0006_user_is_active_user_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_profile_complete',
        ),
    ]
