# Generated by Django 3.2.25 on 2025-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0007_remove_user_is_active_remove_user_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
