# Generated by Django 5.1.6 on 2025-04-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0008_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
