# Generated by Django 5.1.6 on 2025-04-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0008_remove_product_store_remove_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='is_store_active',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='store_logo',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='merchant',
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('is_store_active', models.BooleanField(default=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='madewithlove_app.category')),
                ('merchant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='madewithlove_app.merchantprofile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='madewithlove_app.store'),
        ),
    ]
