# Generated by Django 5.1.6 on 2025-04-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0009_remove_customerprofile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='merchant',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant', to='madewithlove_app.store'),
        ),
    ]
