# Generated by Django 5.1.6 on 2025-04-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0009_remove_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
