# Generated by Django 5.1.6 on 2025-04-14 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0012_alter_product_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='madewithlove_app.customerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madewithlove_app.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
