# Generated by Django 5.1.6 on 2025-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0012_user_groups_user_is_active_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='payout_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
