# Generated by Django 5.1.6 on 2025-04-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madewithlove_app', '0014_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[('fashion', 'Fashion & Apparel'), ('electronics', 'Electronics & Gadgets'), ('beauty', 'Beauty & Personal Care'), ('handmade', 'Handmade & Crafts'), ('food', 'Food & Specialty'), ('books', 'Books & Stationery'), ('home', 'Home & Kitchen'), ('local', 'Local & Cultural'), ('other', 'other')], default='other', max_length=50, unique=True),
        ),
    ]
